import { Book } from "@/lib/types";

export const fallbackBooks: Book[] = [
  {
    id: 901,
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Romans",
    isbn: "9780525559474",
    description: "Un roman contemporain tres demande autour des choix de vie et des possibles.",
    availableCopies: 3,
    isAvailable: true,
    publishedAt: "2020-08-13",
  },
  {
    id: 902,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Sciences",
    isbn: "9780735211292",
    description: "Un guide de reference sur les habitudes et les petits changements durables.",
    availableCopies: 2,
    isAvailable: true,
    publishedAt: "2018-10-16",
  },
  {
    id: 903,
    title: "Anne of Green Gables",
    author: "L.M. Montgomery",
    category: "Jeunesse",
    isbn: "9780553213133",
    description: "Un classique jeunesse tres lu, plein d imagination et de chaleur.",
    availableCopies: 1,
    isAvailable: false,
    publishedAt: "1908-01-01",
  },
  {
    id: 904,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "Sciences",
    isbn: "9780062316110",
    description: "Un essai majeur sur l histoire humaine, souvent demande en consultation.",
    availableCopies: 4,
    isAvailable: true,
    publishedAt: "2011-01-01",
  },
  {
    id: 905,
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Romans",
    isbn: "9780375842207",
    description: "Une fiction marquante qui reste parmi les titres les plus apprecies.",
    availableCopies: 2,
    isAvailable: true,
    publishedAt: "2005-03-14",
  },
  {
    id: 906,
    title: "Charlotte's Web",
    author: "E.B. White",
    category: "Jeunesse",
    isbn: "9780064400558",
    description: "Une lecture familiale douce et intemporelle.",
    availableCopies: 5,
    isAvailable: true,
    publishedAt: "1952-10-15",
  },
  {
    id: 907,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Sciences",
    isbn: "9780374533557",
    description: "Un ouvrage tres consulte sur la decision, les biais et la cognition.",
    availableCopies: 1,
    isAvailable: false,
    publishedAt: "2011-10-25",
  },
  {
    id: 908,
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    category: "Patrimoine",
    isbn: "9781982134196",
    description: "Un roman sur la memoire des bibliotheques et la transmission des livres.",
    availableCopies: 3,
    isAvailable: true,
    publishedAt: "2021-02-09",
  },
  {
    id: 909,
    title: "The Reading List",
    author: "Sara Nisha Adams",
    category: "Romans",
    isbn: "9780063025288",
    description: "Une histoire chaleureuse autour des livres, des lecteurs et du lien social.",
    availableCopies: 2,
    isAvailable: true,
    publishedAt: "2021-08-03",
  },
  {
    id: 910,
    title: "A Rover's Story",
    author: "Jasmine Warga",
    category: "Jeunesse",
    isbn: "9780062956699",
    description: "Un recit jeunesse scientifique tres populaire chez les jeunes lecteurs.",
    availableCopies: 3,
    isAvailable: true,
    publishedAt: "2022-09-13",
  },
  {
    id: 911,
    title: "The Library Book",
    author: "Susan Orlean",
    category: "Patrimoine",
    isbn: "9781476740188",
    description: "Un hommage passionnant au monde des bibliotheques et a leurs archives.",
    availableCopies: 2,
    isAvailable: true,
    publishedAt: "2018-10-16",
  },
  {
    id: 912,
    title: "Brief Answers to the Big Questions",
    author: "Stephen Hawking",
    category: "Sciences",
    isbn: "9781984819190",
    description: "Une introduction accessible a de grandes questions scientifiques.",
    availableCopies: 2,
    isAvailable: true,
    publishedAt: "2018-10-16",
  },
];
